// Central site configuration. NEXT_PUBLIC_* values are inlined at build time,
// so changing them on Netlify requires a redeploy.

export const SITE_URL = "https://www.akilea.si";

// An empty URL hides the link.
export const SOCIAL_LINKS = {
  facebook: "https://www.facebook.com/akileaholistic/",
  instagram: "https://www.instagram.com/AKILEA_HOLISTIC/",
} as const;

export const WEB3FORMS_KEY = process.env.NEXT_PUBLIC_WEB3FORMS_KEY ?? "";

export function isOnlinePaymentEnabled(): boolean {
  return process.env.NEXT_PUBLIC_ENABLE_ONLINE_PAYMENT === "true";
}

// Generated by src/app/opengraph-image.tsx. Segments that set their own
// `openGraph` replace the inherited image, so they spread this back in.
export const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Holistični center & intuitivna masaža Koper | Akilea",
};
